### ISSUE TITLE
Ошибка в лабораторной 

### ISSUE THREAD

**Issue by Giruch1221** [banshchikovalex/Lab_6#1]
Указано неправильное число при функции Random. Четвертая машина никогда не будет выбрана

![-unbx7cc7og](https://cloud.githubusercontent.com/assets/29053251/26676110/a7fca996-46f0-11e7-9cc8-b8582c7fbadb.jpg)

**Comment by banshchikovalex** [comment]
Здравствуйте! Благодарю за внимательность, ошибка исправлена.

**Comment by Giruch1221** [comment]
Все хорошо!
